"""PipelineToSVPass — populate ``ir.rtl_modules`` from the synthesised pipeline IR."""
from __future__ import annotations

import logging
from typing import Any, List

from zuspec.synth.passes.synth_pass import SynthPass
from zuspec.synth.ir.synth_ir import SynthConfig, SynthIR

_log = logging.getLogger(__name__)


class PipelineToSVPass(SynthPass):
    """Convert ``ir.pipeline_ir`` + ``ir.stage_sv`` to ``RTLRawModule`` objects in ``ir.rtl_modules``.

    This pass makes the RTL module structure explicit in ``ir.rtl_modules``
    so that ``SVEmitPass`` can use ``SVEmitter`` rather than calling
    ``_generate_pipeline_sv`` directly.

    Each logical section of the SV file is wrapped in an ``RTLRawModule``:

    - ``__preamble__``   — header comments, timescale, and payload typedefs
    - ``fifo_sync``      — the shallow-FIFO template (always emitted)
    - ``skid_buffer``    — the skid-buffer template (only when a deep channel exists)
    - ``<regfile>``      — register-file module (5-stage pipelines)
    - ``<scoreboard>``   — scoreboard module(s) (when an IndexedPool is declared)
    - ``<StageName>``    — one entry per pipeline stage
    - ``<TopLevel>``     — the top-level wrapper module
    - ``__epilogue__``   — lint-off/on guards

    The lines stored in each ``RTLRawModule`` are exactly the lines that
    ``_generate_pipeline_sv`` would have extended into its flat ``out`` list,
    so ``SVEmitter.emit_all(ir.rtl_modules)`` produces **identical** text.

    If ``ir.pipeline_ir`` is ``None`` (FSM-only path), this pass is a no-op.

    Args:
        config: Synthesis configuration.
        module_prefix: Optional prefix prepended to all emitted module names.
            Should match the value passed to ``SVEmitPass``.
    """

    def __init__(self, config: SynthConfig, *, module_prefix: str = "") -> None:
        super().__init__(config=config)
        self._module_prefix = module_prefix

    @property
    def name(self) -> str:
        return "pipeline_to_sv"

    def run(self, ir: SynthIR) -> SynthIR:
        if ir.pipeline_ir is None:
            _log.debug("[PipelineToSVPass] no pipeline_ir — skipping")
            return ir

        from zuspec.synth.mls import (
            _SKID_DEPTH_THRESHOLD,
            _gen_payload_typedefs,
            _gen_regfile_module,
            _gen_stage_module_generic,
            _gen_toplevel,
            _get_xlen,
            _pfx,
            _read_fifo_template,
            _read_skid_template,
        )
        from zuspec.be.sv.ir import RTLRawModule

        pip = ir.pipeline_ir
        pfx = self._module_prefix
        comp_name = (
            getattr(ir.component, "__name__", "Component") if ir.component else "Component"
        )
        xlen = _get_xlen(ir)
        modules: List[RTLRawModule] = []

        # ── Preamble ─────────────────────────────────────────────────────────
        preamble: List[str] = []
        preamble.append("/* verilator lint_off MULTITOP */")
        preamble.append(
            f"// Auto-generated by zuspec-synth  (component={comp_name}, config={ir.config!r})"
        )
        preamble.append("// SystemVerilog (IEEE 1800-2017) — Yosys/Verilator compatible")
        preamble.append("`timescale 1ns/1ps")
        preamble.append(
            f"// Pipeline: {pip.pipeline_stages} stages — "
            + ", ".join(s.name for s in pip.stages)
        )
        preamble.append("")
        preamble.extend(_gen_payload_typedefs(xlen, pfx))
        modules.append(RTLRawModule(name="__preamble__", lines=preamble))

        # ── fifo_sync template ────────────────────────────────────────────────
        try:
            fifo_text = _read_fifo_template()
            if pfx:
                fifo_text = fifo_text.replace(
                    "module fifo_sync", f"module {_pfx(pfx, 'fifo_sync')}", 1
                )
            modules.append(RTLRawModule(name="fifo_sync", lines=[fifo_text]))
        except OSError as exc:
            _log.warning("[PipelineToSVPass] could not read fifo_sync.v: %s", exc)

        # ── skid_buffer template (deep channels only) ─────────────────────────
        has_deep = any(ch.depth > _SKID_DEPTH_THRESHOLD for ch in pip.channels)
        if has_deep:
            try:
                skid_text = _read_skid_template()
                if pfx:
                    skid_text = skid_text.replace(
                        "module skid_buffer", f"module {_pfx(pfx, 'skid_buffer')}", 1
                    )
                modules.append(RTLRawModule(name="skid_buffer", lines=[skid_text]))
            except OSError as exc:
                _log.warning(
                    "[PipelineToSVPass] could not read skid_buffer.v: %s", exc
                )

        # ── Register-file module (5-stage pipelines) ──────────────────────────
        stage_names = {s.name for s in pip.stages}
        if "RegReadStage" in stage_names:
            meta = getattr(ir, "meta", None)
            if meta is not None and getattr(meta, "regfiles", None):
                from zuspec.synth.sprtl.sv_codegen import generate_regfile_sv

                rf_sv = generate_regfile_sv(meta, module_prefix=pfx)
                if rf_sv:
                    modules.append(RTLRawModule(name="__regfile__", lines=[rf_sv, ""]))
            else:
                modules.append(
                    RTLRawModule(
                        name="regfile_rv",
                        lines=_gen_regfile_module(xlen, pfx),
                    )
                )

        # ── IndexedPool scoreboard modules ────────────────────────────────────
        meta = getattr(ir, "meta", None)
        if (
            meta is not None
            and getattr(meta, "indexed_pools", None)
            and "RegReadStage" in stage_names
        ):
            from zuspec.synth.sprtl.indexed_pool_synth import (
                IndexedPoolHazardAnalyzer,
                IndexedPoolSVGenerator,
            )

            _analyzer = IndexedPoolHazardAnalyzer()
            _pool_gen = IndexedPoolSVGenerator()
            for pool_decl in meta.indexed_pools:
                pool_hazards = _analyzer.analyze(pool_decl)
                sb_sv = _pool_gen.generate(pool_decl, pool_hazards, module_prefix=pfx)
                modules.append(
                    RTLRawModule(name=f"{pool_decl.field_name}_scoreboard", lines=[sb_sv, ""])
                )

        # ── Per-stage modules ─────────────────────────────────────────────────
        stage_sv_map: dict = getattr(ir, "stage_sv", {})
        for stage in pip.stages:
            if stage.name in stage_sv_map:
                lines = list(stage_sv_map[stage.name])
            else:
                lines = _gen_stage_module_generic(stage, pfx)
            modules.append(RTLRawModule(name=stage.name, lines=lines))

        # ── Top-level wrapper ─────────────────────────────────────────────────
        top_lines = _gen_toplevel(pip, ir, pfx)
        modules.append(RTLRawModule(name=pip.module_name, lines=top_lines))

        # ── Epilogue ──────────────────────────────────────────────────────────
        modules.append(
            RTLRawModule(name="__epilogue__", lines=["/* verilator lint_on MULTITOP */", ""])
        )

        ir.rtl_modules = modules
        _log.info(
            "[PipelineToSVPass] populated ir.rtl_modules with %d module entries",
            len(modules),
        )
        return ir
