#****************************************************************************
# Copyright 2019-2025 Matthew Ballance and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#****************************************************************************
"""Emit a SystemVerilog rand class from a zuspec dataclass.

Translates ``@zdc.dataclass`` definitions into SV ``class``/``endclass``
declarations with ``rand`` field declarations and ``constraint`` blocks.
No benchmark-specific knowledge (DPI timing, module harness) lives here.
"""
import math
from typing import Any, Dict, List, Optional, Tuple


class SVRandClassEmitter:
    """Translate a zuspec dataclass into a SV rand class declaration.

    Usage::

        emitter = SVRandClassEmitter()
        sv_text = emitter.emit_class(MemTransaction)
        # sv_text is the 'class ... endclass' string, ready to include in SV

    The emitter reads field metadata via ``zdc.extract_rand_fields()`` and
    parses constraint method bodies via ``zdc.ConstraintParser``.
    """

    # Map Python bin_op IR operators to SV equivalents
    _BINOP_MAP: Dict[str, str] = {
        '+': '+', '-': '-', '*': '*', '/': '/',
        '%': '%', '//': '/', '<<': '<<', '>>': '>>',
        '|': '|', '^': '^', '&': '&',
    }

    # Map Python compare IR operators to SV equivalents
    _CMPOP_MAP: Dict[str, str] = {
        '==': '==', '!=': '!=',
        '<': '<', '<=': '<=', '>': '>', '>=': '>=',
    }

    def emit_class(self, cls: type) -> str:
        """Emit a SV rand class declaration for *cls*.

        Returns a string starting with ``// AUTO-GENERATED`` and ending with
        ``endclass``.  Does **not** include DPI imports or module wrappers.
        """
        import zuspec.dataclasses as zdc

        fields = zdc.extract_rand_fields(cls)
        cp = zdc.ConstraintParser()
        constraints = cp.extract_constraints(cls)

        lines: List[str] = []
        lines.append(f"// AUTO-GENERATED by SVRandClassEmitter — do not edit")
        lines.append(f"// Source: {cls.__module__} :: {cls.__name__}")
        lines.append("")
        lines.append(f"class {cls.__name__};")

        # Field declarations
        for field in fields:
            decl = self._field_decl(field)
            lines.append(f"  {decl}")

        # Domain constraints for list-domain fields (emitted as separate constraint blocks)
        domain_constraints: List[str] = []
        for field in fields:
            domain = field.get('domain')
            if domain is not None and isinstance(domain, (list, tuple)):
                if not isinstance(domain, tuple) or len(domain) != 2:
                    # List domain → inside {v0, v1, ...}
                    vals = ', '.join(self._sv_literal(v) for v in domain)
                    domain_constraints.append(
                        f"  constraint c_{field['name']}_domain "
                        f"{{ {field['name']} inside {{{vals}}}; }}"
                    )
                else:
                    lo, hi = domain
                    sv_lo = self._sv_literal(lo)
                    sv_hi = self._sv_literal(hi)
                    domain_constraints.append(
                        f"  constraint c_{field['name']}_domain "
                        f"{{ {field['name']} inside {{[{sv_lo}:{sv_hi}]}}; }}"
                    )

        if domain_constraints:
            lines.append("")
            lines.extend(domain_constraints)

        # User-defined constraint blocks
        for c in constraints:
            exprs = c.get('exprs', [])
            if not exprs:
                continue
            lines.append("")
            lines.append(f"  constraint {c['name']} {{")
            for expr in exprs:
                sv_expr = self._emit_expr(expr)
                lines.append(f"    {sv_expr};")
            lines.append("  }")

        lines.append("endclass")
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Field width & declaration helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _sv_literal(v: int) -> str:
        """Return a SV integer literal for *v*, sized when needed.

        SV unsized literals default to 32 bits.  Values that don't fit in
        32 bits need an explicit size prefix (e.g. ``64'd1099511627775``).
        """
        if not isinstance(v, int) or isinstance(v, bool):
            return str(v)
        if abs(v) > 0xFFFF_FFFF:
            n_bits = max(64, v.bit_length() + (1 if v < 0 else 0))
            # round up to power-of-2 width (32, 64, 128 ...)
            pw = 1 << (n_bits - 1).bit_length()
            prefix = "-" if v < 0 else ""
            return f"{prefix}{pw}'d{abs(v)}"
        return str(v)

    def _bits_for_domain(self, domain) -> int:
        """Return the minimum bit width to represent all values in *domain*."""
        if isinstance(domain, tuple) and len(domain) == 2:
            lo, hi = domain
            if hi < 0:
                # Signed; not common for rand fields but handle gracefully
                return max(1, math.ceil(math.log2(abs(hi) + 1)) + 1)
            return max(1, math.ceil(math.log2(hi + 1)) if hi > 0 else 1)
        else:
            # List domain
            max_val = max(abs(v) for v in domain) if domain else 0
            return max(1, math.ceil(math.log2(max_val + 1)) if max_val > 0 else 1)

    def _field_decl(self, field: Dict[str, Any]) -> str:
        """Return SV field declaration string, e.g. ``rand bit [7:0] addr;``"""
        name = field['name']
        kind = field.get('kind', 'rand')
        rand_kw = 'randc' if kind == 'randc' else 'rand'
        domain = field.get('domain')
        if domain is not None:
            bits = self._bits_for_domain(domain)
        else:
            bits = 32  # default width when no domain is given

        if bits == 1:
            return f"{rand_kw} bit {name};"
        return f"{rand_kw} bit [{bits - 1}:0] {name};"

    # ------------------------------------------------------------------
    # Expression IR → SV string
    # ------------------------------------------------------------------

    def _emit_expr(self, node: Dict[str, Any]) -> str:
        t = node.get('type')
        if t == 'constant':
            return self._sv_literal(node['value'])
        elif t == 'attribute':
            # Strip 'self.' prefix
            attr = node.get('attr', '')
            return attr
        elif t == 'name':
            return node.get('id', '')
        elif t == 'bin_op':
            op = self._BINOP_MAP.get(node['op'], node['op'])
            left = self._emit_expr(node['left'])
            right = self._emit_expr(node['right'])
            return f"({left} {op} {right})"
        elif t == 'compare':
            return self._emit_compare(node)
        elif t == 'bool_op':
            sv_op = '&&' if node['op'] == 'and' else '||'
            parts = [self._emit_expr(v) for v in node['values']]
            joined = f" {sv_op} ".join(parts)
            return f"({joined})"
        elif t == 'unary_op':
            op = '!' if node['op'] == 'not' else node['op']
            return f"({op}{self._emit_expr(node['operand'])})"
        elif t == 'implies':
            ante = self._emit_expr(node['antecedent'])
            cons = self._emit_expr(node['consequent'])
            return f"({ante}) -> ({cons})"
        else:
            raise ValueError(f"SVRandClassEmitter: unsupported IR node type '{t}'")

    def _emit_compare(self, node: Dict[str, Any]) -> str:
        ops = node['ops']
        comparators = node['comparators']
        left_expr = self._emit_expr(node['left'])

        if len(ops) == 1 and ops[0] == 'in':
            return self._emit_in(left_expr, comparators[0])
        if len(ops) == 1 and ops[0] == 'not_in':
            return f"!({self._emit_in(left_expr, comparators[0])})"

        # Simple comparison or chained comparison (a < b < c → a < b && b < c)
        if len(ops) == 1:
            sv_op = self._CMPOP_MAP.get(ops[0], ops[0])
            right = self._emit_expr(comparators[0])
            return f"{left_expr} {sv_op} {right}"

        # Chained: a op0 b op1 c  →  (a op0 b) && (b op1 c)
        parts: List[str] = []
        operands = [node['left']] + comparators
        for i, op in enumerate(ops):
            sv_op = self._CMPOP_MAP.get(op, op)
            l = self._emit_expr(operands[i])
            r = self._emit_expr(operands[i + 1])
            parts.append(f"{l} {sv_op} {r}")
        return '(' + ' && '.join(parts) + ')'

    def _emit_in(self, left_expr: str, comparator: Dict[str, Any]) -> str:
        """Emit ``left inside {range_or_list}``."""
        t = comparator.get('type')
        if t == 'call' and comparator.get('func') == 'range':
            args = comparator.get('args', [])
            if len(args) == 2:
                lo = self._emit_expr(args[0])
                hi_val = self._emit_expr(args[1])
                return f"{left_expr} inside {{[{lo}:{hi_val}]}}"
        if t == 'list':
            elems = comparator.get('elements', [])
            vals = ', '.join(self._emit_expr(e) for e in elems)
            return f"{left_expr} inside {{{vals}}}"
        # Fallback: treat comparator as single value
        return f"{left_expr} == {self._emit_expr(comparator)}"
